(lp0
S'102 Struts: Duplicate Validation Forms'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'103 Struts: Incomplete validate() Method Definition'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'105 Struts: Form Field Without Validator'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'106 Struts: Plug-in Framework not in Use'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'107 Struts: Unused Validation Form'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'108 Struts: Unvalidated Action Form'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'109 Struts: Validator Turned Off'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'110 Struts: Validator Without Form Field'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'112 Missing XML Validation'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"113 Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Response Splitting')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'115 Misinterpretation of Input'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'116 Improper Encoding or Escaping of Output'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'117 Improper Output Neutralization for Logs'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'123 Write-what-where Condition'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'130 Improper Handling of Length Parameter Inconsistency '
p1
aS' C C++ All'
p2
aS''
p3
a.(lp0
S'134 Uncontrolled Format String'
p1
aS' C C++ Perl Languages that support format strings'
p2
aS'top25'
p3
a.(lp0
S'135 Incorrect Calculation of Multi-Byte String Length'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'138 Improper Neutralization of Special Elements'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'140 Improper Neutralization of Delimiters'
p1
aS''
p2
ag2
a.(lp0
S'141 Improper Neutralization of Parameter/Argument Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'142 Improper Neutralization of Value Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'143 Improper Neutralization of Record Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'144 Improper Neutralization of Line Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'145 Improper Neutralization of Section Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'146 Improper Neutralization of Expression/Command Delimiters'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'147 Improper Neutralization of Input Terminators'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'148 Improper Neutralization of Input Leaders'
p1
aS''
p2
ag2
a.(lp0
S'149 Improper Neutralization of Quoting Syntax'
p1
aS''
p2
ag2
a.(lp0
S'150 Improper Neutralization of Escape Meta or Control Sequences'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'151 Improper Neutralization of Comment Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'152 Improper Neutralization of Macro Symbols'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'153 Improper Neutralization of Substitution Characters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'154 Improper Neutralization of Variable Name Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'155 Improper Neutralization of Wildcards or Matching Symbols'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'156 Improper Neutralization of Whitespace'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'157 Failure to Sanitize Paired Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'158 Improper Neutralization of Null Byte or NUL Character'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'159 Failure to Sanitize Special Element'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'160 Improper Neutralization of Leading Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'161 Improper Neutralization of Multiple Leading Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'162 Improper Neutralization of Trailing Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'163 Improper Neutralization of Multiple Trailing Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'164 Improper Neutralization of Internal Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'165 Improper Neutralization of Multiple Internal Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'166 Improper Handling of Missing Special Element'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'167 Improper Handling of Additional Special Element'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'168 Improper Handling of Inconsistent Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'170 Improper Null Termination'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'172 Encoding Error'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'173 Improper Handling of Alternate Encoding'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'174 Double Decoding of the Same Data'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'175 Improper Handling of Mixed Encoding'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'176 Improper Handling of Unicode Encoding'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'177 Improper Handling of URL Encoding (Hex Encoding)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'178 Improper Handling of Case Sensitivity'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'185 Incorrect Regular Expression'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'186 Overly Restrictive Regular Expression'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'20 Improper Input Validation'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S"22 Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
p1
aS' Language-independent'
p2
aS'top25'
p3
a.(lp0
S'226 Sensitive Information Uncleared Before Release'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'23 Relative Path Traversal'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'231 Improper Handling of Extra Values'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'232 Improper Handling of Undefined Values'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'233 Parameter Problems'
p1
aS''
p2
ag2
a.(lp0
S'234 Failure to Handle Missing Parameter'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'235 Improper Handling of Extra Parameters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'236 Improper Handling of Undefined Parameters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"24 Path Traversal: '../filedir'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"25 Path Traversal: '/../filedir'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"26 Path Traversal: '/dir/../filename'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"27 Path Traversal: 'dir/../../filename'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"28 Path Traversal: '..\\filedir'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"29 Path Traversal: '\\..\\filename'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"30 Path Traversal: '\\dir\\..\\filename'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"31 Path Traversal: 'dir\\..\\..\\filename'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"32 Path Traversal: '...' (Triple Dot)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"33 Path Traversal: '....' (Multiple Dot)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"34 Path Traversal: '....//'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"35 Path Traversal: '.../...//'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'358 Improperly Implemented Security Check for Standard'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'36 Absolute Path Traversal'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"37 Path Traversal: '/absolute/pathname/here'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"38 Path Traversal: '\\absolute\\pathname\\here'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"39 Path Traversal: 'C:dirname'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"40 Path Traversal: '\\\\UNC\\share\\name\\' (Windows UNC Share)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'41 Improper Resolution of Path Equivalence'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"42 Path Equivalence: 'filename.' (Trailing Dot)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"43 Path Equivalence: 'filename....' (Multiple Trailing Dot)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"44 Path Equivalence: 'file.name' (Internal Dot)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"45 Path Equivalence: 'file...name' (Multiple Internal Dot)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'450 Multiple Interpretations of UI Input'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'454 External Initialization of Trusted Variables or Data Stores'
p1
aS' PHP Language-independent'
p2
aS''
p3
a.(lp0
S"46 Path Equivalence: 'filename ' (Trailing Space)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"47 Path Equivalence: ' filename' (Leading Space)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"48 Path Equivalence: 'file name' (Internal Whitespace)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"49 Path Equivalence: 'filename/' (Trailing Slash)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"50 Path Equivalence: '//multiple/leading/slash'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"51 Path Equivalence: '/multiple//internal/slash'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"52 Path Equivalence: '/multiple/trailing/slash//'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"53 Path Equivalence: '\\multiple\\\\internal\\backslash'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"54 Path Equivalence: 'filedir\\' (Trailing Backslash)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"55 Path Equivalence: '/./' (Single Dot Directory)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'554 ASP.NET Misconfiguration: Not Using Input Validation Framework'
p1
aS' .NET'
p2
aS''
p3
a.(lp0
S"56 Path Equivalence: 'filedir*' (Wildcard)"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'564 SQL Injection: Hibernate'
p1
aS''
p2
ag2
a.(lp0
S'566 Authorization Bypass Through User-Controlled SQL Primary Key'
p1
aS''
p2
ag2
a.(lp0
S"57 Path Equivalence: 'fakedir/../realdir/filename'"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'58 Path Equivalence: Windows 8.3 Filename'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'606 Unchecked Input for Loop Condition'
p1
aS''
p2
ag2
a.(lp0
S'624 Executable Regular Expression Error'
p1
aS' PHP Perl'
p2
aS''
p3
a.(lp0
S'625 Permissive Regular Expression'
p1
aS' Perl PHP'
p2
aS''
p3
a.(lp0
S'627 Dynamic Variable Evaluation'
p1
aS' PHP Perl'
p2
aS''
p3
a.(lp0
S"643 Improper Neutralization of Data within XPath Expressions ('XPath Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'644 Improper Neutralization of HTTP Headers for Scripting Syntax'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'647 Use of Non-Canonical URL Paths for Authorization Decisions'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S"652 Improper Neutralization of Data within XQuery Expressions ('XQuery Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'67 Improper Handling of Windows Device Names'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'73 External Control of File Name or Path'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"74 Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'75 Failure to Sanitize Special Elements into a Different Plane (Special Element Injection)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'76 Improper Neutralization of Equivalent Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"77 Improper Neutralization of Special Elements used in a Command ('Command Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'777 Regular Expression without Anchors'
p1
aS''
p2
ag2
a.(lp0
S"78 Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')"
p1
aS' All'
p2
aS'top25'
p3
a.(lp0
S"79 Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
p1
aS' Language-independent'
p2
aS'top25'
p3
a.(lp0
S'790 Improper Filtering of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'791 Incomplete Filtering of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'792 Incomplete Filtering of One or More Instances of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'793 Only Filtering One Instance of a Special Element'
p1
aS''
p2
ag2
a.(lp0
S'794 Incomplete Filtering of Multiple Instances of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'795 Only Filtering Special Elements at a Specified Location'
p1
aS''
p2
ag2
a.(lp0
S'796 Only Filtering Special Elements Relative to a Marker'
p1
aS''
p2
ag2
a.(lp0
S'797 Only Filtering Special Elements at an Absolute Position'
p1
aS''
p2
ag2
a.(lp0
S'80 Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'807 Reliance on Untrusted Inputs in a Security Decision'
p1
aS' Language-independent'
p2
aS'top25'
p3
a.(lp0
S'81 Improper Neutralization of Script in an Error Message Web Page'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'82 Improper Neutralization of Script in Attributes of IMG Tags in a Web Page'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'83 Improper Neutralization of Script in Attributes in a Web Page'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'838 Inappropriate Encoding for Output Context'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'84 Improper Neutralization of Encoded URI Schemes in a Web Page'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'85 Doubled Character XSS Manipulations'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'86 Improper Neutralization of Invalid Characters in Identifiers in Web Pages'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'87 Improper Neutralization of Alternate XSS Syntax'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'88 Argument Injection or Modification'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"89 Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
p1
aS' All'
p2
aS'top25'
p3
a.(lp0
S"90 Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'91 XML Injection (aka Blind XPath Injection)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"93 Improper Neutralization of CRLF Sequences ('CRLF Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"94 Improper Control of Generation of Code ('Code Injection')"
p1
aS' Interpreted languages'
p2
aS''
p3
a.(lp0
S"95 Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')"
p1
aS' Java Javascript Python Perl PHP Ruby Interpreted Languages'
p2
aS''
p3
a.(lp0
S"96 Improper Neutralization of Directives in Statically Saved Code ('Static Code Injection')"
p1
aS' PHP Perl All Interpreted Languages'
p2
aS''
p3
a.(lp0
S'97 Improper Neutralization of Server-Side Includes (SSI) Within a Web Page'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"98 Improper Control of Filename for Include/Require Statement in PHP Program ('PHP File Inclusion')"
p1
aS' PHP'
p2
aS''
p3
a.(lp0
S"99 Improper Control of Resource Identifiers ('Resource Injection')"
p1
aS' All'
p2
aS''
p3
