(lp0
S'116 Improper Encoding or Escaping of Output'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'14 Compiler Removal of Code to Clear Buffers'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'179 Incorrect Behavior Order: Early Validation'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'195 Signed to Unsigned Conversion Error'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'196 Unsigned to Signed Conversion Error'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'197 Numeric Truncation Error'
p1
aS' C C++ Java .NET'
p2
aS''
p3
a.(lp0
S'198 Use of Incorrect Byte Ordering'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'222 Truncation of Security-relevant Information'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"300 Channel Accessible by Non-Endpoint ('Man-in-the-Middle')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'302 Authentication Bypass by Assumed-Immutable Data'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'319 Cleartext Transmission of Sensitive Information'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'471 Modification of Assumed-Immutable Data (MAID)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'472 External Control of Assumed-Immutable Web Parameter'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'473 PHP External Variable Modification'
p1
aS' PHP'
p2
aS''
p3
a.(lp0
S'552 Files or Directories Accessible to External Parties'
p1
aS''
p2
ag2
a.(lp0
S'565 Reliance on Cookies without Validation and Integrity Checking'
p1
aS''
p2
ag2
a.(lp0
S'582 Array Declared Public Final and Static'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'642 External Control of Critical State Data'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'681 Incorrect Conversion between Numeric Types'
p1
aS' Language-Independent'
p2
aS''
p3
a.(lp0
S'682 Incorrect Calculation'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'683 Function Call With Incorrect Order of Arguments'
p1
aS''
p2
ag2
a.(lp0
S'704 Incorrect Type Conversion or Cast'
p1
aS' C C++ All'
p2
aS''
p3
a.(lp0
S'733 Compiler Optimization Removal or Modification of Security-critical Code'
p1
aS' C C++ All Compiled Languages'
p2
aS''
p3
a.(lp0
S'88 Argument Injection or Modification'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"89 Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
p1
aS' All'
p2
aS'top25'
p3
a.(lp0
S"90 Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'91 XML Injection (aka Blind XPath Injection)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"93 Improper Neutralization of CRLF Sequences ('CRLF Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"94 Improper Control of Generation of Code ('Code Injection')"
p1
aS' Interpreted languages'
p2
aS''
p3
a.(lp0
S"95 Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')"
p1
aS' Java Javascript Python Perl PHP Ruby Interpreted Languages'
p2
aS''
p3
a.(lp0
S"96 Improper Neutralization of Directives in Statically Saved Code ('Static Code Injection')"
p1
aS' PHP Perl All Interpreted Languages'
p2
aS''
p3
a.(lp0
S'97 Improper Neutralization of Server-Side Includes (SSI) Within a Web Page'
p1
aS' All'
p2
aS''
p3
