(lp0
S"113 Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Response Splitting')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'116 Improper Encoding or Escaping of Output'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'138 Improper Neutralization of Special Elements'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'141 Improper Neutralization of Parameter/Argument Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'142 Improper Neutralization of Value Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'143 Improper Neutralization of Record Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'144 Improper Neutralization of Line Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'145 Improper Neutralization of Section Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'146 Improper Neutralization of Expression/Command Delimiters'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'147 Improper Neutralization of Input Terminators'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'150 Improper Neutralization of Escape Meta or Control Sequences'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'151 Improper Neutralization of Comment Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'152 Improper Neutralization of Macro Symbols'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'153 Improper Neutralization of Substitution Characters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'154 Improper Neutralization of Variable Name Delimiters'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'155 Improper Neutralization of Wildcards or Matching Symbols'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'156 Improper Neutralization of Whitespace'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'158 Improper Neutralization of Null Byte or NUL Character'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'160 Improper Neutralization of Leading Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'161 Improper Neutralization of Multiple Leading Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'162 Improper Neutralization of Trailing Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'163 Improper Neutralization of Multiple Trailing Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'164 Improper Neutralization of Internal Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'165 Improper Neutralization of Multiple Internal Special Elements'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'198 Use of Incorrect Byte Ordering'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'20 Improper Input Validation'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'212 Improper Cross-boundary Removal of Sensitive Data'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S"300 Channel Accessible by Non-Endpoint ('Man-in-the-Middle')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'311 Missing Encryption of Sensitive Data'
p1
aS' Language-independent'
p2
aS'top25'
p3
a.(lp0
S'319 Cleartext Transmission of Sensitive Information'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'322 Key Exchange without Entity Authentication'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'326 Inadequate Encryption Strength'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'353 Missing Support for Integrity Check'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"402 Transmission of Private Resources into a New Sphere ('Resource Leak')"
p1
aS''
p2
ag2
a.(lp0
S'406 Insufficient Control of Network Message Volume (Network Amplification)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'434 Unrestricted Upload of File with Dangerous Type'
p1
aS' ASP.NET PHP Language-independent'
p2
aS'top25'
p3
a.(lp0
S'5 J2EE Misconfiguration: Data Transmission Without Encryption'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'502 Deserialization of Untrusted Data'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'514 Covert Channel'
p1
aS''
p2
ag2
a.(lp0
S'515 Covert Storage Channel'
p1
aS''
p2
ag2
a.(lp0
S'566 Authorization Bypass Through User-Controlled SQL Primary Key'
p1
aS''
p2
ag2
a.(lp0
S'602 Client-Side Enforcement of Server-Side Security'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'603 Use of Client-Side Authentication'
p1
aS''
p2
ag2
a.(lp0
S"652 Improper Neutralization of Data within XQuery Expressions ('XQuery Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'669 Incorrect Resource Transfer Between Spheres'
p1
aS''
p2
ag2
a.(lp0
S'691 Insufficient Control Flow Management'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'707 Improper Enforcement of Message or Data Structure'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"74 Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"757 Selection of Less-Secure Algorithm During Negotiation ('Algorithm Downgrade')"
p1
aS''
p2
ag2
a.(lp0
S"77 Improper Neutralization of Special Elements used in a Command ('Command Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"78 Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')"
p1
aS' All'
p2
aS'top25'
p3
a.(lp0
S"79 Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
p1
aS' Language-independent'
p2
aS'top25'
p3
a.(lp0
S'790 Improper Filtering of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'791 Incomplete Filtering of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'792 Incomplete Filtering of One or More Instances of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'793 Only Filtering One Instance of a Special Element'
p1
aS''
p2
ag2
a.(lp0
S'794 Incomplete Filtering of Multiple Instances of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'795 Only Filtering Special Elements at a Specified Location'
p1
aS''
p2
ag2
a.(lp0
S'796 Only Filtering Special Elements Relative to a Marker'
p1
aS''
p2
ag2
a.(lp0
S'797 Only Filtering Special Elements at an Absolute Position'
p1
aS''
p2
ag2
a.(lp0
S'80 Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'830 Inclusion of Web Functionality from an Untrusted Source'
p1
aS''
p2
ag2
a.(lp0
S'838 Inappropriate Encoding for Output Context'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S"89 Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
p1
aS' All'
p2
aS'top25'
p3
a.(lp0
S"90 Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'91 XML Injection (aka Blind XPath Injection)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"93 Improper Neutralization of CRLF Sequences ('CRLF Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"94 Improper Control of Generation of Code ('Code Injection')"
p1
aS' Interpreted languages'
p2
aS''
p3
a.(lp0
S"95 Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')"
p1
aS' Java Javascript Python Perl PHP Ruby Interpreted Languages'
p2
aS''
p3
a.(lp0
S"96 Improper Neutralization of Directives in Statically Saved Code ('Static Code Injection')"
p1
aS' PHP Perl All Interpreted Languages'
p2
aS''
p3
a.(lp0
S'97 Improper Neutralization of Server-Side Includes (SSI) Within a Web Page'
p1
aS' All'
p2
aS''
p3
