(lp0
S'12 ASP.NET Misconfiguration: Missing Custom Error Page'
p1
aS' .NET'
p2
aS''
p3
a.(lp0
S'128 Wrap-around Error'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'172 Encoding Error'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'193 Off-by-one Error'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'194 Unexpected Sign Extension'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'195 Signed to Unsigned Conversion Error'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'196 Unsigned to Signed Conversion Error'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'197 Numeric Truncation Error'
p1
aS' C C++ Java .NET'
p2
aS''
p3
a.(lp0
S'198 Use of Incorrect Byte Ordering'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'209 Information Exposure Through an Error Message'
p1
aS' PHP All'
p2
aS''
p3
a.(lp0
S'210 Information Exposure Through Generated Error Message'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'211 Information Exposure Through External Error Message'
p1
aS' PHP All'
p2
aS''
p3
a.(lp0
S'248 Uncaught Exception'
p1
aS' C++ Java .NET'
p2
aS''
p3
a.(lp0
S'252 Unchecked Return Value'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'390 Detection of Error Condition Without Action'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'391 Unchecked Error Condition'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'392 Missing Report of Error Condition'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'393 Return of Wrong Status Code'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'394 Unexpected Status Code or Return Value'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'435 Interaction Error'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'455 Non-exit on Failed Initialization'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'544 Missing Standardized Error Handling Mechanism'
p1
aS''
p2
ag2
a.(lp0
S'550 Information Exposure Through Server Error Message'
p1
aS''
p2
ag2
a.(lp0
S'626 Null Byte Interaction Error (Poison Null Byte)'
p1
aS' PHP Perl ASP.NET'
p2
aS''
p3
a.(lp0
S'754 Improper Check for Unusual or Exceptional Conditions'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'755 Improper Handling of Exceptional Conditions'
p1
aS' Language-Independent'
p2
aS''
p3
