(lp0
S"113 Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Response Splitting')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'114 Process Control'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'115 Misinterpretation of Input'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'123 Write-what-where Condition'
p1
aS' C C++'
p2
aS''
p3
a.(lp0
S'134 Uncontrolled Format String'
p1
aS' C C++ Perl Languages that support format strings'
p2
aS'top25'
p3
a.(lp0
S'15 External Control of System or Configuration Setting'
p1
aS''
p2
ag2
a.(lp0
S'183 Permissive Whitelist'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'184 Incomplete Blacklist'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'20 Improper Input Validation'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S"22 Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
p1
aS' Language-independent'
p2
aS'top25'
p3
a.(lp0
S'233 Parameter Problems'
p1
aS''
p2
ag2
a.(lp0
S'250 Execution with Unnecessary Privileges'
p1
aS' All'
p2
aS'top25'
p3
a.(lp0
S'266 Incorrect Privilege Assignment'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'267 Privilege Defined With Unsafe Actions'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'268 Privilege Chaining'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'269 Improper Privilege Management'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'272 Least Privilege Violation'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'276 Incorrect Default Permissions'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'282 Improper Ownership Management'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'283 Unverified Ownership'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'285 Improper Authorization'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'286 Incorrect User Management'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'287 Improper Authentication'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'308 Use of Single-factor Authentication'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'309 Use of Password System for Primary Authentication'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'317 Plaintext Storage in GUI'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'356 Product UI does not Warn User of Unsafe Actions'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'357 Insufficient UI Warning of Dangerous Operations'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'434 Unrestricted Upload of File with Dangerous Type'
p1
aS' ASP.NET PHP Language-independent'
p2
aS'top25'
p3
a.(lp0
S'436 Interpretation Conflict'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'446 UI Discrepancy for Security Feature'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'447 Unimplemented or Unsupported Feature in UI'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'448 Obsolete Feature in UI'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'449 The UI Performs the Wrong Action'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'450 Multiple Interpretations of UI Input'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'451 UI Misrepresentation of Critical Information'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"470 Use of Externally-Controlled Input to Select Classes or Code ('Unsafe Reflection')"
p1
aS' Java PHP Interpreted languages'
p2
aS''
p3
a.(lp0
S'471 Modification of Assumed-Immutable Data (MAID)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'494 Download of Code Without Integrity Check'
p1
aS' Language-independent'
p2
aS'top25'
p3
a.(lp0
S'506 Embedded Malicious Code'
p1
aS''
p2
ag2
a.(lp0
S'507 Trojan Horse'
p1
aS''
p2
ag2
a.(lp0
S'508 Non-Replicating Malicious Code'
p1
aS''
p2
ag2
a.(lp0
S'509 Replicating Malicious Code (Virus or Worm)'
p1
aS''
p2
ag2
a.(lp0
S'510 Trapdoor'
p1
aS''
p2
ag2
a.(lp0
S'511 Logic/Time Bomb'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'512 Spyware'
p1
aS''
p2
ag2
a.(lp0
S'521 Weak Password Requirements'
p1
aS''
p2
ag2
a.(lp0
S'538 File and Directory Information Exposure'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'549 Missing Password Field Masking'
p1
aS''
p2
ag2
a.(lp0
S'552 Files or Directories Accessible to External Parties'
p1
aS''
p2
ag2
a.(lp0
S'553 Command Shell in Externally Accessible Directory'
p1
aS''
p2
ag2
a.(lp0
S'554 ASP.NET Misconfiguration: Not Using Input Validation Framework'
p1
aS' .NET'
p2
aS''
p3
a.(lp0
S'566 Authorization Bypass Through User-Controlled SQL Primary Key'
p1
aS''
p2
ag2
a.(lp0
S'592 Authentication Bypass Issues'
p1
aS''
p2
ag2
a.(lp0
S'6 J2EE Misconfiguration: Insufficient Session-ID Length'
p1
aS' Java'
p2
aS''
p3
a.(lp0
S'602 Client-Side Enforcement of Server-Side Security'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'603 Use of Client-Side Authentication'
p1
aS''
p2
ag2
a.(lp0
S'613 Insufficient Session Expiration'
p1
aS''
p2
ag2
a.(lp0
S'620 Unverified Password Change'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'639 Authorization Bypass Through User-Controlled Key'
p1
aS' Language-independent'
p2
aS''
p3
a.(lp0
S'640 Weak Password Recovery Mechanism for Forgotten Password'
p1
aS' All'
p2
aS''
p3
a.(lp0
S'641 Improper Restriction of Names for Files and Other Resources'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"77 Improper Neutralization of Special Elements used in a Command ('Command Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"78 Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')"
p1
aS' All'
p2
aS'top25'
p3
a.(lp0
S"79 Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
p1
aS' Language-independent'
p2
aS'top25'
p3
a.(lp0
S'790 Improper Filtering of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'791 Incomplete Filtering of Special Elements'
p1
aS''
p2
ag2
a.(lp0
S'88 Argument Injection or Modification'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"89 Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
p1
aS' All'
p2
aS'top25'
p3
a.(lp0
S"90 Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S'91 XML Injection (aka Blind XPath Injection)'
p1
aS' All'
p2
aS''
p3
a.(lp0
S"93 Improper Neutralization of CRLF Sequences ('CRLF Injection')"
p1
aS' All'
p2
aS''
p3
a.(lp0
S"94 Improper Control of Generation of Code ('Code Injection')"
p1
aS' Interpreted languages'
p2
aS''
p3
a.(lp0
S"95 Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')"
p1
aS' Java Javascript Python Perl PHP Ruby Interpreted Languages'
p2
aS''
p3
